title = 'Foojank'
baseURL = 'https://foojank.com/'
languageCode = 'en-us'
enableInlineShortcodes = true
enableGitInfo = true

[params]
displayUpdatedDate = true
dateFormat = "January 2, 2006"

[params.theme]
default = 'dark'
displayToggle = false

[module.imports]
path = 'github.com/imfing/hextra'

[caches]
[caches.images]
dir = ':cacheDir/images'

[menu]
main = [
    { name = 'Install', pageRef = '/docs/install', weight = 1 },
    { name = 'Documentation', pageRef = '/docs', weight = 2 },
    { name = 'Search', params = { type = 'search' }, weight = 3 },
    { name = 'GitHub', url = 'https://github.com/fooHQ/foojank', params = { icon = 'github' }, weight = 4 },
]
sidebar = [
    { name = 'Resources', params = { type = 'separator' }, weight = 1 },
    { name = 'Support', pageRef = '/support', weight = 2 },
]